import "package:flutter/material.dart";
import "package:go_router/go_router.dart";

import "../../theme/forge_theme.dart";
import "../../theme/tokens.dart";
import "../../widgets/banner_note.dart";
import "../../widgets/gold_button.dart";
import "../../widgets/hero_band.dart";
import "../../widgets/phone_scaffold.dart";
import "../../widgets/section_label.dart";

/// The Terms of Use and Privacy Policy, presented at sign-up.
///
/// This is a demonstration draft. It is written to cover the product
/// comprehensively — identity, likeness consent, vouching, rewards, privacy,
/// and disputes — and it says so honestly: final language for every
/// jurisdiction is prepared and reviewed by licensed counsel before launch.
/// The screen never pretends a draft is a finished legal instrument.
class LegalTerms extends StatelessWidget {
  const LegalTerms({super.key});

  static const List<(String, String)> _sections = <(String, String)>[
    (
      "Who we are",
      "FORGE Talent Connections is operated by FORGE LINK LLC, a "
          "Florida limited liability company. These terms are the "
          "agreement between you and FORGE LINK LLC, covering every part "
          "of the product: profiles, verification, vouching, projects, "
          "messaging, the rewards and referral program, and exports.",
    ),
    (
      "Agreeing to these terms",
      "Creating an account, signing in, or continuing to use "
          "FORGE Talent Connections means you accept these terms and the "
          "privacy policy below. If you do not accept them, do not use "
          "the product.",
    ),
    (
      "Eligibility and one account per person",
      "You must have reached the age of majority where you live — 18 in "
          "Florida — and you may hold exactly one account, created for "
          "yourself, with your own true identity. Accounts created for "
          "someone else, shared, purchased, or operated by software are "
          "not permitted and can be closed.",
    ),
    (
      "Your identity, likeness, and consent",
      "Verification can involve checking your identity against records you "
          "provide. Your likeness — photos, video, and any AI-generated "
          "presenter of you — is used only with your recorded consent, "
          "which you can withdraw at any time. Anything AI-generated "
          "carries a visible AI-generated label wherever it appears. An "
          "AI likeness is only ever generated when the verification "
          "confidence meets the required threshold; below it, nothing is "
          "produced. Florida law protects your name and likeness from "
          "unauthorized commercial use; nothing of yours is published or "
          "used commercially without your recorded permission.",
    ),
    (
      "Verification and seals",
      "Checks, seals, matches, and every other decision are made by our "
          "systems and reviewed by people — never silently. You can request "
          "human review of any decision about you. A record that fails its "
          "check stays locked and is never presented as verified.",
    ),
    (
      "Vouching and accountability",
      "A vouch is a signed, recorded statement that stays attached to your "
          "name. Vouches can be revoked, revocations are recorded, and "
          "misuse of vouching reduces your own standing. The ledger of "
          "vouches you give is public on your profile.",
    ),
    (
      "Rewards, referrals, and prizes",
      "The rewards program awards points for verified actions only. "
          "Points must be earned personally, by you as an individual "
          "person: points generated by a company, bot, script, AI agent, "
          "automation, purchased or pooled accounts, or any other "
          "non-human means are void. Every prize award is preceded by a "
          "human audit. Breaking these rules voids prizes, forfeits "
          "points, and can end your membership; conduct that also breaks "
          "the law — fraud, impersonation, unauthorized automation — can "
          "be referred to law enforcement. No purchase is necessary to "
          "earn points or win, prizes are not exchangeable for cash "
          "unless the official rules say otherwise, winners are "
          "responsible for applicable taxes, and the program is void "
          "where prohibited by law. Each prize period is governed by "
          "official rules published before it starts. The program is "
          "operated from Florida as a competition of verified skill and "
          "effort — winners are determined by audited points, never by "
          "chance. If any prize period instead qualifies as a game "
          "promotion under chapter 849 of the Florida Statutes, its "
          "official rules are filed with the State of Florida and the "
          "prize pool is secured as that chapter requires before the "
          "period begins.",
    ),
    (
      "Your privacy",
      "We collect what the product needs to work: your account details, "
          "the records you submit for verification, your activity inside "
          "projects, and device information for security. We use it to "
          "run the product, verify work, prevent abuse, and improve the "
          "service. We never sell your personal information. You can "
          "access, correct, export, and delete your data from Settings; "
          "verified records you exported remain yours. Data is retained "
          "only as long as the product or the law requires. The product "
          "is not directed at children.",
    ),
    (
      "Security",
      "Records are sealed with tamper-evident signatures, transport is "
          "encrypted, and access inside the company is limited to what a "
          "task requires. No system is perfectly secure; if a breach "
          "affects you, you will be told what happened and what we are "
          "doing about it within the time Florida law sets — no more "
          "than 30 days.",
    ),
    (
      "Acceptable use",
      "No impersonation, no false statements in vouches or records, no "
          "harassment, no scraping or automated access, no attempts to "
          "defeat verification, and no use of the product to break the "
          "law. We can suspend or close accounts that do these things, "
          "and every suspension can be appealed to a person.",
    ),
    (
      "Disputes, governing law, and where claims go",
      "These terms are governed by the laws of the State of Florida, "
          "and legal disputes belong in the courts located in Florida — "
          "except where the law of your home jurisdiction gives you "
          "rights that cannot be limited. Most problems are fixed "
          "fastest through support and human review, so start there. "
          "The final terms name the specific venue and any dispute "
          "process — including arbitration terms and your rights in "
          "small claims court — in the language each jurisdiction "
          "requires.",
    ),
    (
      "Changes and contact",
      "If these terms change in a way that matters, you will be told in "
          "the app before the change applies. Questions and privacy "
          "requests: legal@forgetalentconnections.com.",
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final ForgeTheme forge = ForgeTheme.of(context);

    return PhoneScaffold(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          const SizedBox(height: ForgeSpacing.gapSection),
          const Align(alignment: Alignment.centerRight, child: DemoBadge()),
          const SizedBox(height: 8),
          HeroBand(
            title: "Terms & Privacy",
            subtitle: "The whole agreement, in plain language",
            onBack: () => context.go("/create-profile"),
          ),
          const SizedBox(height: ForgeSpacing.gapSection),
          // Honest framing first: a draft is never presented as a finished
          // legal instrument.
          const BannerNote(
            tone: BannerTone.governance,
            text: "Demonstration draft. Before launch, licensed counsel "
                "prepares and reviews the final terms for every "
                "jurisdiction where FORGE Talent Connections operates.",
          ),
          const SizedBox(height: ForgeSpacing.gapSection),
          for (final (String title, String body) in _sections) ...<Widget>[
            SectionLabel(title),
            const SizedBox(height: 6),
            ForgeCard(
              child: Text(
                body,
                style: TextStyle(
                  fontFamily: ForgeType.bodyFamily,
                  fontSize: ForgeType.caption,
                  height: 1.45,
                  color: forge.text,
                ),
              ),
            ),
            const SizedBox(height: ForgeSpacing.gapCard),
          ],
          const SizedBox(height: ForgeSpacing.gapCard),
          GoldButton(
            label: "Back to Sign-Up",
            onPressed: () => context.go("/create-profile"),
          ),
          const SizedBox(height: 24),
        ],
      ),
    );
  }
}
